= Welcome to OpenZeppelin Documentation!

Learn about developing, upgrading and deploying your smart contract applications

We have three different components to help you solve all your smart contract needs. Each one builds on top of the previous one. Our contracts library is our cornerstone product, a secure foundation for your solidity needs. Our SDK gives you a tool suite to interact with your smart contracts and the starter kits help you tie it all together with a consumer-ready frontend.


== Why use OpenZeppelin tools?

OpenZeppelin has been the bedrock of smart contract development in Ethereum for the last few years. Our libraries have been used by more than 100K developers to create tokens, protect digital assets and power decentralized applications. It has helped developers secure more than $4.5 billion in digital assets.

As the ecosystem matures, we are taking all the lessons we have learned during this journey to help you create professional applications that are ready for consumer adoption.

[.card.card-contracts]
.xref:contracts::index.adoc[Contracts]
--
A library of modular, reusable, secure smart contracts, written in Solidity.

[.card-cta]#xref:contracts::index.adoc[Get started >]#
--

[.card.card-sdk]
.xref:sdk::index.adoc[SDK]
--
A suite of tools to help you develop, test, upgrade and deploy smart contracts.

[.card-cta]#xref:sdk::index.adoc[Get started >]#
--

[.card.card-starter-kits]
.xref:starter-kits::index.adoc[Starter Kits]
--
Bundles to kickstart your decentralized web application.

[.card-cta]#xref:starter-kits::index.adoc[Get started >]#
--

== Gas Station Network (Beta)

Gas Station Network is a service that you can integrate in your dapp to abstract all transaction and gas costs,

More information about Gas Station Network.

https://gifted-mayer-c163b8.netlify.com/[Website]
https://medium.com/@rrecuero/eth-onboarding-solution-90607fb81380[Announcement]

=== Components
In order to integrate Gas Station Network into your application, you need to slightly modify your contracts with OpenZeppelin library and then connect to a new provider via web3.

* *Contracts*: See how to use OpenZeppelin Library to integrate GSN https://docs.openzeppelin.com/contracts/2.x/gsn[here].
* *Fund your dapp recipient*: Use the dapp tool to fund your application https://gifted-mayer-c163b8.netlify.com/recipients[here].
* *Web3 Provider*: You can see an example of how to integrate it using [oz.js] in the https://github.com/OpenZeppelin/gsn-sample-chat_app/blob/master/client/src/App.js[sample app]. More documentation is coming soon.

=== Sample App: Chat
We have created a sample chat application to showcase the power of gasless dapps. As you can see you don't need Metamask or any other wallet to interact with it.

See it in action https://gsn-chat-app.openzeppelin.com/[here]
Github Repo[https://github.com/OpenZeppelin/gsn-sample-chat_app]

CAUTION: Gas Station Network is still in beta. It is only live on Rinkeby. We plan to release it to mainnet during August. Then, it will stay in beta for a few months.
