:page-toc:

= H1 - Crowdsales - Test

Crowdsales are a popular use for Ethereum; they let you allocate tokens to network participants in various ways, mostly in exchange for Ether. They come in a variety of shapes and flavors, so let's go over the various types available in OpenZeppelin and how to use them.
Crowdsales have a bunch of different properties, but here are some important ones:

== H2 - Crowdsales Rate

Understanding the rate of a crowdsale is super important, and mistakes here are a common source of bugs. Firstly, all currency math is done in the smallest unit of that currency and converted to the correct decimal places when displaying the currency.
This means that when you do math in your smart contracts, you need to understand that you're adding, dividing, and multiplying the smallest amount of a currency (like wei), not the commonly-used displayed value of the currency (Ether).

=== H3 - But First, Coffee a Primer on Tokens

Simply put, a token isn't anything special. In Ethereum, pretty much everything is a contract, and that includes what we call tokens. "Sending a token" is the same as "calling a method on a smart contract that someone wrote and deployed". And, at the end of the day, a token is just a mapping of addresses to balances and some nice methods to add and subtract from those balances.

==== H4 - Code Blocks

Simply put, a token isn't anything special. In Ethereum, pretty much everything is a contract, and that includes what we call tokens. "Sending a token" is the same as "calling a method on a smart.

----
require 'asciidoctor'

puts Asciidoctor.convert_file 'mysample.adoc', to_file: false
----

[source,rust]
----
require 'asciidoctor'

puts Asciidoctor.convert_file 'mysample.adoc', to_file: false
----

[%header,cols="4*"]
|===
a|
Contracts

 a|
Parameters Name

 a|
Parameters Type

 a|
Inline Functions

|`ERC20Burnable` | [.primary]`account` | [.secondary]`address` | [.light]`decimals()`
|`ERC20Burnable` | [.primary]`account` | [.secondary]`address` | [.light]`decimals()`
|`ERC20Burnable` | [.primary]`account` | [.secondary]`address` | [.light]`decimals()`

|===


NOTE: Tip: For an overview of ERC20 tokens and a walkthrough on how to create a token contract, read our ERC20 guide.

TIP: Tip: For an overview of ERC20 tokens and a walkthrough on how to create a token contract, read our ERC20 guide.

WARNING: Tip: For an overview of ERC20 tokens and a walkthrough on how to create a token contract, read our ERC20 guide.

=== Custom Alerts

[.alert.tip]
OpenZeppelin has a 5 week release cycle, every five weeks a new release is published.

[.alert.note--secondary]
OpenZeppelin has a 5 week release cycle, every five weeks a new release is published.

[.alert.tip--secondary]
Tip: For a detailed writeup see our guide How to implement supply mechanisms.

[.alert.warning--secondary]
Warning: This page is incomplete. We're working to improve it for the next release.


== ERC 721

This set of interfaces, contracts, and utilities are all related to the `ERC721` Non-Fungible Token Standard.

NOTE: For an overview of ERC20 tokens and a walkthrough on how to create a token contract, read our ERC20 guide.

For a walkthrough on how to create an `ERC721` token read our `ERC721` guide.

The EIP consists of three interfaces, found here as `IERC721`, `IERC721Metadata`, and `IERC721Enumerable`. Only the first one is required in a contract to be ERC721 compliant.

Each interface is implemented separately in `ERC721`, `ERC721Metadata`, and `ERC721Enumerable`. You can choose the subset of functionality you would like to support in your token by combining the desired subset through inheritance.

The fully featured token implementing all three interfaces is prepackaged as `ERC721Full`.

Additionally, `IERC721Receiver` can be used to prevent tokens from becoming forever locked in contracts. Imagine sending an in-game item to an exchange address that can't send it back!. When using safeTransferFrom(), the token contract checks to see that the receiver is an `IERC721Receiver`, which implies that it knows how to handle `ERC721` tokens. If you're writing a contract that needs to receive ERC721 tokens, you'll want to include this interface.

Finally, some custom extensions are also included:

* `ERC721Mintable` — like the ERC20 version, this allows certain addresses to mint new tokens
* `ERC721Pausable` — like the ERC20 version, this allows addresses to freeze transfers of tokens

WARNING: This page is incomplete. We're working to improve it for the next release. Stay tuned!

== Core

=== IERC720
Interface of the ERC20 standard as defined in the EIP. Does not include the optional functions; to access them see ERC20Detailed.

[.description]
.Functions
****
* <<IERC720.ownerOf>>
* <<IERC720.balanceOf>>
* <<IERC720.transferFrom>>
* <<IERC720.setApprovalForAll>>
****

[.description]
.Events
****
* <<IERC720.Transfer>>
* <<IERC720.Approval>>
* <<IERC720.ApprovalForAll>>
****

[[IERC720.ownerOf]]
[.function]
.ownerOf(address owner) → [secondary]`uint256` [function__type]#public#
****
	Returns the number of NFTs in owner's account.
****

[[IERC720.balanceOf]]
[.function]
.balanceOf(address owner) → [secondary]`uint256` [function__type]#public#
****
	Returns the number of NFTs in owner's account.
****

[[IERC720.transferFrom]]
[.function]
.transferFrom(address owner) → [secondary]`uint256` [function__type]#internal#
****
	Returns the number of NFTs in owner's account.
****

[[IERC720.setApprovalForAll]]
[.function]
.setApprovalForAll(address owner) → [primary]`bool` [function__type]#private#
****
Transfers a specific NFT (tokenId) from one account (from) to another (to).

.Requirements:
* from, to cannot be zero.
* tokenId must be owned by from.
* If the caller is not from, it must be have been allowed to move this NFT by either approve or setApproveForAll.
****

[[IERC720.Transfer]]
[.event]
.Transfer(address owner) → [secondary]`uint256` [function__type]#payable external#
****
	Moves `amount` tokens from the caller's account to recipient.      .
	Returns a boolean value indicating whether the operation succeeded.
	Emits a `Transfer` event.
****

[[IERC720.Approval]]
[.event]
.Approval(address owner) → [secondary]`uint256` [function__type]#external#
****
	Moves `amount` tokens from the caller's account to recipient.      .
	Returns a boolean value indicating whether the operation succeeded.
	Emits a `Transfer` event.
****

[[IERC720.ApprovalForAll]]
[.event]
.ApprovalForAll(address owner) → [secondary]`uint256` [function__type]#payable external#
****
	Moves `amount` tokens from the caller's account to recipient.      .
	Returns a boolean value indicating whether the operation succeeded.
	Emits a `Transfer` event.
****
