= OpenZeppelin Documentation

Learn about writing, testing, deploying, and upgrading your smart contract applications on Ethereum using the OpenZeppelin tools.

Our offering includes the most widely used Solidity smart contracts library, a command-line tool for managing your project, several JavaScript modules, and pre-packaged boxes to bootstrap development.

== Why OpenZeppelin?

OpenZeppelin tools have been built with *security in mind*. Since the first release of the Contracts library in 2016, our libraries have been downloaded over 1.5 million times to create tokens, protect digital assets, and power decentralized applications, securing more than $4.5 billion. We also work with top Ethereum projects through our https://openzeppelin.com/security-audits/[security audits service].

== Learn

Comprehensive guides for every step of your development journey.

include::learn::partial$cards.adoc[]

Check out https://forum.openzeppelin.com/c/general/guides-and-tutorials/23[the OpenZeppelin forum] for additional community-contributed guides!

== Tools & Libraries

All the open source tools and libraries built and maintained by the OpenZeppelin team:

[.card.card-primary.card-contracts]
--
xref:contracts::index.adoc[[.card-title]#Contracts# [.card-body]#A library of modular+++,+++ reusable+++,+++ and secure smart contracts+++,+++ written in Solidity.#]
--

[.card.card-primary.card-upgrades-js]
--
xref:upgrades-plugins::index.adoc[[.card-title]#Upgrades# [.card-body]#Plugins for Buidler and Truffle to deploy and manage upgradeable contracts on Ethereum.#]
--

[.card.card-primary.card-test-helpers]
--
xref:test-helpers::index.adoc[[.card-title]#Test Helpers# [.card-body]#A JavaScript library of common assertions for testing smart contracts.#]
--

[.card.card-secondary.card-solidity-docgen]
--
https://github.com/OpenZeppelin/solidity-docgen[[.card-title]#Solidity Docgen# [.card-body]#A tool for automatically generating documentation based on the natspec comments of your Solidity contracts.#]
--

[.card.card-secondary.card-test-environment]
--
xref:test-environment::index.adoc[[.card-title]#Test Environment# [.card-body]#A JavaScript library for creating a testing environment for contracts+++,+++ which plays nice with Mocha+++,+++ Ava+++,+++ and Jest.#]
--

== More from OpenZeppelin

=== Audits

The OpenZeppelin Research team provides a https://openzeppelin.com/security-audits/[Security Audits] service for decentralized applications, tools, and protocols. You can browse through past public audits in https://blog.openzeppelin.com/security-audits/[our blog]. Go through our https://blog.openzeppelin.com/follow-this-quality-checklist-before-an-audit-8cc6a0e44845/[quality checklist] and mailto:audits@openzeppelin.com[contact us] before xref:learn::preparing-for-mainnet.adoc[going to production] to make sure your project is secure.

=== Ethernaut

Learn more about security in Solidity contracts by playing https://ethernaut.openzeppelin.com/[Ethernaut]. Every level in Ethernaut is a smart contract waiting to be hacked, and teaches you a vulnerability by having you exploit it - many of them based on real-life hacks! You can discuss your solutions or ask for tips in https://forum.openzeppelin.com/c/security/ethernaut/30[our forum].

=== Careers

The OpenZeppelin https://openzeppelin.com/about/[team] is always hiring. If you have enjoyed using our tools or reading our audit reports, and want to be a part of it, check out our https://openzeppelin.com/jobs/[current job openings] and join us!

=== Social

// We may want to remove this if it's going to be present on the footer?
You can https://forum.openzeppelin.com/[join our Forum], https://blog.openzeppelin.com/[check out our Blog], https://twitter.com/OpenZeppelin[follow us on Twitter], or https://www.youtube.com/channel/UC0Nx8RbugiCzdlVGK7hWZfw/videos[tune in our YouTube channel]!

== Questions?

Join the OpenZeppelin community in https://forum.openzeppelin.com/[our forum] to https://forum.openzeppelin.com/c/support/17[ask for help], as well as share your feedback or showcase what you have built with OpenZeppelin!

== Share the Love!

If you are using OpenZeppelin contracts, tools, or libraries in your project, share the love with the rest of the community by adding a badge to your `README`! Let your audience know that your system is built with the most secure components available.

image::https://img.shields.io/badge/built%20with-OpenZeppelin-3677FF[built-with openzeppelin]


```markdown
[![built-with openzeppelin](https://img.shields.io/badge/built%20with-OpenZeppelin-3677FF)](https://docs.openzeppelin.com/)
```
