= Documentation

Explore our guides and examples to learn how to integrate OpenZeppelin security products with your project.

[.card-section]
== Explore using OpenZeppelin

OpenZeppelin provides a complete suite of security products to adopt security best practices from the first line of code all the way to running your decentralized application on-chain.

[.card-section.card-section-2col]
====
[.card.card-primary.card-contracts]
--
xref:contracts::index.adoc[[.card-title]#Contracts# [.card-body]#pass:q[A library of modular, reusable, and secure smart contracts, written in Solidity.]#]
--

[.card.card-primary.card-defender]
--
xref:defender::index.adoc[[.card-title]#Defender# [.card-body]#pass:q[A mission-critical developer security platform to code, audit, deploy, monitor, and operate blockchain applications.]#]
--
====

[.card.card-secondary.card-community]
--
xref:community-contracts::index.adoc[[.card-title]#Community Contracts# [.card-body]#pass:q[A community-driven extension of our Solidity library.]#]
--

[.card.card-secondary.card-upgrades]
--
xref:upgrades.adoc[[.card-title]#Upgrades# [.card-body]#pass:q[A comprehensive suite of contracts and tooling to deploy and manage upgradeable contracts on Ethereum.]#]
--

[.card.card-secondary.card-contracts-cairo]
--
xref:contracts-cairo::index.adoc[[.card-title]#Contracts for Cairo# [.card-body]#pass:q[A library for secure smart contract development written in Cairo for Starknet.]#]
--

[.card.card-secondary.card-contracts-stylus]
--
xref:contracts-stylus::index.adoc[[.card-title]#Contracts for Stylus# [.card-body]#pass:q[A library for secure smart contract development written in Rust for Arbitrum Stylus.]#]
--

[.card.card-secondary.card-substrate-runtimes]
--
xref:substrate-runtimes::index.adoc[[.card-title]#Substrate Runtimes# [.card-body]#pass:q[A collection of runtime templates for parachain development on Polkadot.]#]
--

[.card.card-secondary.card-uniswap-hooks]
--
xref:stellar-contracts::index.adoc[[.card-title]#Stellar Contracts# [.card-body]#pass:q[OpenZeppelin Contracts written in Rust for Stellar Soroban.]#]
--

[.card.card-secondary.card-uniswap-hooks]
--
xref:uniswap-hooks::index.adoc[[.card-title]#Uniswap Hooks# [.card-body]#pass:q[A Solidity library for secure and modular Uniswap hooks.]#]
--

[.card.card-secondary.card-solidity-docgen]
--
https://github.com/OpenZeppelin/solidity-docgen[[.card-title]#Solidity Docgen# [.card-body]#pass:q[A tool for automatically generating documentation based on the natspec comments of your Solidity contracts.]#]
--

=== Security Audits

OpenZeppelin security audits are trusted by leading organizations building decentralized systems. Browse through past public audits in our https://blog.openzeppelin.com/security-audits/[blog] and follow our https://blog.openzeppelin.com/follow-this-quality-checklist-before-an-audit-8cc6a0e44845/[quality checklist] before going to production. To learn more about OpenZeppelin’s audit process and request an audit, please visit our https://openzeppelin.com/security-audits/[security audits site].

[.card-section]
== Learn

Comprehensive guides for every step of your development journey.

include::learn::partial$cards.adoc[]

Check out https://forum.openzeppelin.com/c/general/guides-and-tutorials/23[the OpenZeppelin forum] for additional community-contributed guides!

=== Ethernaut

Learn more about security in Solidity contracts by playing https://ethernaut.openzeppelin.com/[Ethernaut]. Every level in Ethernaut is a smart contract waiting to be hacked, and teaches you a vulnerability by having you exploit it - many of them based on real-life hacks! You can discuss your solutions or ask for tips in https://forum.openzeppelin.com/c/security/ethernaut/30[our forum].

== More from OpenZeppelin

=== Careers

OpenZeppelin is growing. If you enjoy using our products or reading our audit reports, and have a genuine interest in protecting the open economy, please check out our current https://openzeppelin.com/jobs/[job openings].

== Questions?

Join the OpenZeppelin community in https://forum.openzeppelin.com/[our forum] to https://forum.openzeppelin.com/c/support/17[ask for help], as well as share your feedback or showcase what you have built with OpenZeppelin!

== Share the Love!

If you are using OpenZeppelin contracts, tools, or libraries in your project, share the love with the rest of the community by adding a badge to your `README`! Let your audience know that your system is built with the most secure components available.

image::https://img.shields.io/badge/built%20with-OpenZeppelin-3677FF[built-with openzeppelin]


```markdown
[![built-with openzeppelin](https://img.shields.io/badge/built%20with-OpenZeppelin-3677FF)](https://docs.openzeppelin.com/)
```
