= Documentation

Explore our guides, references, and examples to build with OpenZeppelin.

[.card-section]
== Explore using OpenZeppelin

OpenZeppelin provides a complete suite of security products to build, manage, and inspect all aspects of software development and operations for Ethereum projects.

[.card.card-primary.card-contracts]
--
xref:contracts::index.adoc[[.card-title]#Contracts# [.card-body]#pass:q[A library of modular, reusable, and secure smart contracts, written in Solidity.]#]
--

[.card.card-primary.card-upgrades-js]
--
xref:upgrades.adoc[[.card-title]#Upgrades# [.card-body]#pass:q[A comprehensive suite of contracts and tooling to deploy and manage upgradeable contracts on Ethereum.]#]
--

[.card.card-primary.card-defender]
--
xref:defender::index.adoc[[.card-title]#Defender# [.card-body]#pass:q[A secure platform to automate Ethereum operations.]#]
--

[.card.card-secondary.card-subgraphs]
--
xref:subgraphs::index.adoc[[.card-title]#Subgraphs# [.card-body]#pass:q[Subgraphs to easily index the activity of contracts built with OpenZeppelin Contracts.]#]
--

[.card.card-secondary.card-test-helpers]
--
xref:test-helpers::index.adoc[[.card-title]#Test Helpers# [.card-body]#pass:q[A JavaScript library of common assertions for testing smart contracts.]#]
--

[.card.card-secondary.card-solidity-docgen]
--
https://github.com/OpenZeppelin/solidity-docgen[[.card-title]#Solidity Docgen# [.card-body]#pass:q[A tool for automatically generating documentation based on the natspec comments of your Solidity contracts.]#]
--

=== Security Audits

OpenZeppelin security audits are trusted by leading organizations building decentralized systems. Browse through past public audits in our https://blog.openzeppelin.com/security-audits/[blog] and follow our https://blog.openzeppelin.com/follow-this-quality-checklist-before-an-audit-8cc6a0e44845/[quality checklist] before going to production. To learn more about OpenZeppelin’s audit process and request an audit, please visit our https://openzeppelin.com/security-audits/[security audits site].

[.card-section]
== Learn

Comprehensive guides for every step of your development journey.

include::learn::partial$cards.adoc[]

Check out https://forum.openzeppelin.com/c/general/guides-and-tutorials/23[the OpenZeppelin forum] for additional community-contributed guides!

=== Ethernaut

Learn more about security in Solidity contracts by playing https://ethernaut.openzeppelin.com/[Ethernaut]. Every level in Ethernaut is a smart contract waiting to be hacked, and teaches you a vulnerability by having you exploit it - many of them based on real-life hacks! You can discuss your solutions or ask for tips in https://forum.openzeppelin.com/c/security/ethernaut/30[our forum].

[.section-bg]
== More from OpenZeppelin

=== Careers

OpenZeppelin is growing. If you enjoy using our products or reading our audit reports, and have a genuine interest in protecting the open economy, please check out our current https://openzeppelin.com/jobs/[job openings].

== Questions?

Join the OpenZeppelin community in https://forum.openzeppelin.com/[our forum] to https://forum.openzeppelin.com/c/support/17[ask for help], as well as share your feedback or showcase what you have built with OpenZeppelin!

== Share the Love!

If you are using OpenZeppelin contracts, tools, or libraries in your project, share the love with the rest of the community by adding a badge to your `README`! Let your audience know that your system is built with the most secure components available.

image::https://img.shields.io/badge/built%20with-OpenZeppelin-3677FF[built-with openzeppelin]


```markdown
[![built-with openzeppelin](https://img.shields.io/badge/built%20with-OpenZeppelin-3677FF)](https://docs.openzeppelin.com/)
```
