= Setting Up a Node Project

New software industries often start out with every project sharing the same technology stack. The Ethereum ecosystem is no exception, and the language of choice is https://en.wikipedia.org/wiki/JavaScript[JavaScript]. All of the most used Ethereum libraries, including OpenZeppelin software, are written in JavaScript or one of its variants.

JavaScript code is traditionally run on a web browser as part of a website, but it can be also executed as a standalone process using https://nodejs.org[Node].

This guide will help you get your Node development environment set up, which you'll need to use the different OpenZeppelin tools and other third party products.

TIP: If you are already familiar with Node, npm and Git, feel free to skip this guide!

== Installing Node

There are multiple ways to get Node on your machine: you can get it either  via a https://nodejs.org/en/download/package-manager/[package manager] or by downloading https://nodejs.org/en/download/[the installer] directly.

Once you're done, run `node --version` on a terminal to check your installation: any version of the 10.x or 12.x line should be compatible with most Ethereum software.

```console
$ node --version
v10.16.3
```

== Creating npm Packages

JavaScript software is often blunded in _packages_, which are distributed via the https://www.npmjs.com/[npm registry]. A package is simply a directory that contains a file called `package.json`, describing the package's name, version, content, and others.

All Node installations include a command-line client for the npm registry, which you'll use while developing your own projects. To start a new project, create a directory for it and run:

```console
$ npm init
```

Simple as that! Your newly created `package.json` file will evolve as your project grows, such as when installing dependencies with `npm install`.

TIP: JavaScript and npm are some of the most used software tools in the world: if you're ever in doubt, you'll find plenty of information about them online.

[[using-npx]]
=== Using `npx`

There are two broads type of packages stored in the npm registry: _libraries_ and _executables_. Installed libraries are used like any other piece of JavaScript code, but executables are special.

A third binary was included when installing node: https://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner[`npx`]. This is used to run executables installed locally in your project.

Some OpenZeppelin tools (like the xref:cli::index.adoc[CLI]) are executables intended to be run using `npx`. Not including `npx` will cause errors due to the binary not bieng in the system path, so for clarity we'll display the full command in our guides:

```console
$ openzeppelin init
openzeppelin: command not found
$ npx openzeppelin init
Welcome to the OpenZeppelin SDK!
```

WARNING: Make sure you are inside your project's directory when running `npx`! Otherwise, it will download the full executable again just to run that command, which most of the time is _not_ what you want.

== Tracking With Version Control

Before you get coding, you should add https://en.wikipedia.org/wiki/Version_control[version control software] to your project to track changes.

By far, the most used tool is https://git-scm.com[Git], often in conjunction with https://github.com[GitHub] for hosting purposes. Indeed, you will find the full source code and history of all OpenZeppelin software in our https://github.com/OpenZeppelin[GitHub repository].

TIP: If you've never used Git before, a good starting place is the https://guides.github.com/introduction/git-handbook/[Git Handbook].
