= Writing automated smart contract tests

In a blockchain environment, a single mistake could cost you all of your funds - or even worse, your users' funds! This guide will help you develop robust applications by writing automated tests that verify your application behaves exactly as you intended.

We'll cover the following topics:

 * <<setting-up-a-testing-environment, Setting up a Testing Environment>>
 * <<writing-unit-tests, Writing Unit Tests>>
 * <<performing-complex-assertions, Performing Complex Assertions>>

include::learn::partial$hardhat-truffle-toggle.adoc[]

== About testing

There is a wide range of testing techniques, from xref:deploying-and-interacting.adoc#interacting-from-the-console[simple manual verifications] to complex end-to-end setups, all of them useful in their own way.

When it comes to smart contract development though, practice has shown that contract https://en.wikipedia.org/wiki/Unit_testing[_unit testing_] is exceptionally worthwhile. These tests are simple to write and quick to run, and let you add features and fix bugs in your code with confidence.

Smart contract unit testing consists of multiple small, focused tests, which each check a small part of your contract for correctness. They can often be expressed in single sentences that make up a specification, such as 'the admin is able to pause the contract', 'transferring tokens emits an event' or 'non-admins cannot mint new tokens'.

[[setting-up-a-testing-environment]]
== Setting up a testing environment

You may be wondering _how_ we're going to run these tests, since smart contracts are executed inside a blockchain. Using the actual Ethereum network would be very expensive, and while testnets are free, they are also slow (with blocktimes between 5 and 20 seconds). If we intend to run hundreds of tests whenever we make a change to our code, we need something better.

What we will use is called a _local blockchain_: a slimmed down version of the real thing, disconnected from the Internet, running on your machine. This will simplify things quite a bit: you won't need to get Ether, and new blocks will be mined instantly.

[[writing-unit-tests]]
== Writing unit tests

We'll use https://www.chaijs.com/[Chai] assertions for our unit tests.

```console
$ npm install --save-dev chai
```

We will keep our test files in a `test` directory. Tests are best structured by mirroring the xref:developing-smart-contracts.adoc#first-contract[`contracts` directory]: for each `.sol` file there, create a corresponding test file.

Time to write our first tests! These will test properties of the `Box` contract xref:developing-smart-contracts.adoc#box-contract[from previous guides]: a simple contract that lets you `retrieve` a value the owner previously `store` d.

[.truffle]
--
We will save the test as `test/Box.test.js`. Each `.test.js` file should have the tests for a single contract, and be named after it.

```js
// test/Box.test.js
// Load dependencies
const { expect } = require('chai');

// Load compiled artifacts
const Box = artifacts.require('Box');

// Start test block
contract('Box', function () {
  beforeEach(async function () {
    // Deploy a new Box contract for each test
    this.box = await Box.new();
  });

  // Test case
  it('retrieve returns a value previously stored', async function () {
    // Store a value
    await this.box.store(42);

    // Test if the returned value is the same one
    // Note that we need to use strings to compare the 256 bit integers
    expect((await this.box.retrieve()).toString()).to.equal('42');
  });
});
```
--

[.hardhat]
--
Create a `test` directory in your project root.  We will save the test as `test/Box.test.js`. Each test `.js` file commonly has the tests for a single contract, and is named after it.

```js
// test/Box.test.js
// Load dependencies
const { expect } = require('chai');

// Start test block
describe('Box', function () {
  before(async function () {
    this.Box = await ethers.getContractFactory('Box');
  });

  beforeEach(async function () {
    this.box = await this.Box.deploy();
    await this.box.deployed();
  });

  // Test case
  it('retrieve returns a value previously stored', async function () {
    // Store a value
    await this.box.store(42);

    // Test if the returned value is the same one
    // Note that we need to use strings to compare the 256 bit integers
    expect((await this.box.retrieve()).toString()).to.equal('42');
  });
});
```
--

TIP: Many books have been written about how to structure unit tests. Check out the https://github.com/MolochVentures/moloch/tree/4e786db8a4aa3158287e0935dcbc7b1e43416e38/test#moloch-testing-guide[Moloch Testing Guide] for a set of principles designed for testing Solidity smart contracts.

We are now ready to run our tests! 

[.truffle]
--
Running `npx truffle test` will execute all tests in the `test` directory, checking that your contracts work the way you meant them to.

NOTE: Make sure you are running a xref:deploying-and-interacting.adoc#local-blockchain[local blockchain].

```console
$ npx truffle test
Using network 'development'.


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



  Contract: Box
    ✓ retrieve returns a value previously stored (38ms)


  1 passing (117ms)
```
--

[.hardhat]
--
Running `npx hardhat test` will execute all tests in the `test` directory, checking that your contracts work the way you meant them to:

```console
$ npx hardhat test


  Box
    ✓ retrieve returns a value previously stored


  1 passing (578ms)
```
--

It's also a very good idea at this point to set up a Continuous Integration service such as https://circleci.com/[CircleCI] to make your tests run automatically every time you commit your code to GitHub.

[[performing-complex-assertions]]
== Performing complex assertions

Many interesting properties of your contracts may be hard to capture, such as:

 * verifying that the contract reverts on errors
 * measuring by how much an account's Ether balance changed
 * checking that the proper events are emitted

xref:test-helpers::index.adoc[*OpenZeppelin Test Helpers*] is a library designed to help you test all of these properties. It will also simplify the tasks of simulating time passing on the blockchain and handling very large numbers.

[.hardhat]
--

NOTE: OpenZeppelin Test Helpers is web3.js based, thus Hardhat users should https://hardhat.org/guides/truffle-testing.html[use the Truffle plugin] for compatibility. However, we recommend instead using https://hardhat.org/hardhat-chai-matchers/docs/overview[Hardhat Chai Matchers] as a better supported alternative for Ethers.js.

--

To install the OpenZeppelin Test Helpers, run:
```console
$ npm install --save-dev @openzeppelin/test-helpers
```

We can then update our tests to use OpenZeppelin Test Helpers for very large number support, to check for an event being emitted and to check that a transaction reverts. 

```javascript
// test/Box.test.js
// Load dependencies
const { expect } = require('chai');

// Import utilities from Test Helpers
const { BN, expectEvent, expectRevert } = require('@openzeppelin/test-helpers');

// Load compiled artifacts
const Box = artifacts.require('Box');

// Start test block
contract('Box', function ([ owner, other ]) {
  // Use large integers ('big numbers')
  const value = new BN('42');

  beforeEach(async function () {
    this.box = await Box.new({ from: owner });
  });

  it('retrieve returns a value previously stored', async function () {
    await this.box.store(value, { from: owner });

    // Use large integer comparisons
    expect(await this.box.retrieve()).to.be.bignumber.equal(value);
  });

  it('store emits an event', async function () {
    const receipt = await this.box.store(value, { from: owner });

    // Test that a ValueChanged event was emitted with the new value
    expectEvent(receipt, 'ValueChanged', { value: value });
  });

  it('non owner cannot store a value', async function () {
    // Test a transaction reverts
    await expectRevert(
      this.box.store(value, { from: other }),
      'Ownable: caller is not the owner',
    );
  });
});
```

These will test properties of the `Ownable` `Box` contract from xref:developing-smart-contracts.adoc#ownable-box-contract[previous guides]: a simple contract that lets you `retrieve` a value the owner previously ``store``d.

Run your tests again to see the Test Helpers in action:

[.truffle]
--
```console
$ npx truffle test
...
  Contract: Box
    ✓ retrieve returns a value previously stored
    ✓ store emits an event
    ✓ non owner cannot store a value (588ms)


  3 passing (753ms)
```
--

[.hardhat]
--
```console
$ npx hardhat test
...
  Contract: Box
    ✓ retrieve returns a value previously stored
    ✓ store emits an event
    ✓ non owner cannot store a value (588ms)


  3 passing (753ms)
```
--

The Test Helpers will let you write powerful assertions without having to worry about the low-level details of the underlying Ethereum libraries. To learn more about what you can do with them, head to their xref:test-helpers::api.adoc[API reference].

== Next steps

Once you have thoroughly tested your contracts and are reasonably sure of their correctness, you'll want to deploy them to a real network and start interacting with them. The following guides will get you up to speed on these topics:

 * xref:connecting-to-public-test-networks.adoc[Connecting to Public Test Networks]
 * xref:deploying-and-interacting.adoc[Deploying and Interacting]
 * xref:preparing-for-mainnet.adoc[Preparing for Mainnet]
