= Sandbox

image:https://github.com/etherisc/depeg-contracts/actions/workflows/build.yml/badge.svg[Build]
https://opensource.org/licenses/Apache-2.0[image:https://img.shields.io/badge/License-Apache_2.0-blue.svg[License]]
https://discord.gg/Qb6ZjgE8[image:https://dcbadge.vercel.app/api/server/cVsgakVG4R?style=flat[image]]

== Fire Insurance Demo

This repository holds the smart contracts for a demo fire insurance.

=== Setup Requirements

[arabic]
. A running Docker installation
. Developing with VS Code
. Working with dev containers

Installing Docker on Windows is sometimes a struggle. Recommended
Approach: Follow the installation instructions for
https://docs.docker.com/desktop/install/windows-install/[Docker
Desktop]. Installing Docker on Linux or Mac should be straight forward.

=== Interaction via Command Line

==== Running Unit Tests

[source,bash]
----
brownie test -n 8
----

==== Deploy and Verify with Ganache

[source,bash]
----
brownie console
----

In the console use the following steps.

[source,python]
----
from scripts.deploy_fire import help
help()
----

The help command then shows an example session.

[source,python]
----
from scripts.deploy_fire import all_in_1, verify_deploy, create_bundle, create_policy, help

(customer, customer2, product, oracle, riskpool, riskpoolWallet, investor, usdc, instance, instanceService, instanceOperator, bundleId, processId, d) = all_in_1(deploy_all=True)

verify_deploy(d, usdc, product)
----

==== Deploy to differnt Network with existing Instance

As an example use the Ganache chain that runs in the background of this
devcontainer setup.

[source,bash]
----
brownie console --network=ganache
----

With an existing instance set parameter `deploy_all=False`. In this case
the file `gif_instance_address.txt` needs to exist and contain the
addresses of the instance registry. The file should be automatically
created during the devconainer setup procedure of this repository.

[source,python]
----
from scripts.deploy_fire import all_in_1, verify_deploy, create_bundle, create_policy, help

(customer, customer2, product, oracle, riskpool, riskpoolWallet, investor, usdc, instance, instanceService, instanceOperator, bundleId, processId, d) = all_in_1(deploy_all=False)

verify_deploy(d, usdc, product)
----