= GSN Provider

**A web3.js compatible provider for sending transactions via the Gas Station Network (GSN)**. This package wraps a modified version of the https://github.com/tabookey/tabookey-gasless/blob/master/src/js/relayclient/RelayClient.js[`RelayClient`] from `tabookey-gasless` with a custom web3 Provider.

== Overview

=== Installation

```console
$ npm install @openzeppelin/gsn-provider
```

=== Usage

Create a `GSNProvider` and use it as the provider for your web3 instance:

```javascript
const Web3 = require("web3");
const { GSNProvider } = require("@openzeppelin/gsn-provider");

const web3 = new Web3(new GSNProvider("http://localhost:8545"));
```

Transactions sent to contracts will then be automatically routed through the GSN:

```javascript
const myContract = new web3.eth.Contract(abi, address);

// Sends the transaction via the GSN
await myContract.methods.myFunction().send({ from });

// Disable GSN for a specific transaction
await myContract.methods.myFunction().send({ from, useGSN: false });
```

== Learn More

* Check out xref:getting-started.adoc[Getting Started] to use GSN Provider in a new project.
* The xref:testing-gsn-applications.adoc[Testing GSN Applications] will teach you how to test your project locally.
* Head to xref:interacting-with-relayhub.adoc[Interacting With `RelayHub`] and the xref:gsn-faq.adoc[GSN Frequently Asked Questions] for more information about its inner workings.
* For detailed usage information, take a look at the xref:api.adoc[API Reference].
